### ISSUE TITLE
Module on the forge throws error upon installation

### ISSUE THREAD

**Issue by pvbouwel** [evenup/evenup-beaver#25]
failed while running: Command puppet module --modulepath /etc/puppet/environments/development/modules upgrade --version=1.2.0 --force evenup/beaver exited with 1: [1;31mError: No such file or directory - /etc/puppet/environments/development/modules/beaver/spec/fixtures/modules/beaver

On the filesystem there is however a file /etc/puppet/environments/development/modules/beaver/spec/fixtures/modules/beaver but this is a symbolic link pointing to /Users/jlambert/Documents/evenup/git/puppet/evenup-beaver

Same for version 1.1.0

Isn't it possible to create a symbolic link with a relative path?  So in this case 'ln -s ../../../../beaver'

Kind regards

**Comment by jlambert121** [comment]
I believe this is no longer the case, the puppet module face incorrectly included symlinks for a while.
