### ISSUE TITLE
Does not work with python module 1.9.6

### ISSUE THREAD

**Issue by ilyash** [evenup/evenup-beaver#42]
Python module 1.9.6 had incompatible change so this module no longer works with 1.9.6. The issue was fixed in 1.9.7. Please update the metadata (about versions compatibility) accordingly. More information at https://github.com/stankevich/puppet-python/issues/230

**Comment by ilyash** [comment]
Wow! Following my report there it's already fixed in 1.9.7.

**Comment by jlambert121** [comment]
I'm going to leave the dependency where it is then since it sounds like 1.9.6 should be pulled.
