### ISSUE TITLE
pip does not get installed

### ISSUE THREAD

**Issue by netrounds-joakim** [evenup/evenup-beaver#43]
I'm new to puppet so I might be missunderstanding something...

But this module has https://forge.puppetlabs.com/stankevich/python as a dependency. But it never uses it? So pip is not installed. Is this by design and the common way to do things?

Just from how I thought it would work, the needed depdendencies would be installed automatically by the puppet module.

So this gives an error that pip isn't installed:

```
    class { 'beaver': }
    beaver::stanza { '/var/log/syslog':
        type    => 'syslog',
        tags    => ['syslog', 'prod'],
    }
```

But simply adding the python stuff myself installs pip:

```
   class { 'python': }  # By default installs pip. Shouldn't this be done in this module instead???
   class { 'beaver': }
   beaver::stanza { '/var/log/syslog':
        type    => 'syslog',
        tags    => ['syslog', 'prod'],
    }
```

I don't seem to be alone thinking this should be done automatically by the beaver puppet module, when I quickly browsed over the forks of this project, here's an example of someone adding the install of pip: https://github.com/obliadp/evenup-beaver/commit/14fbd6761cb81404b791573738aae56f90772fd4

**Comment by jlambert121** [comment]
Sounds reasonable.  I don't use pip so hadn't thought of it.  The inclusion of python (maybe just include 'python' in case someone has it defined elsewhere in their modules) sounds reasonable.  Would you send me a PR?  Probably should only include python if the installation type is pip.
